In [2]:
# press Shift + Tab to get help on function cursor is next to

In [3]:
import numpy as np

In [4]:
myList = [4, 6, 9]

In [5]:
type(myList)

list

In [6]:
np.array(myList)

array([4, 6, 9])

In [7]:
myList

[4, 6, 9]

In [8]:
myArr = np.array(myList)

In [9]:
myArr

array([4, 6, 9])

In [10]:
type(myArr)

numpy.ndarray

In [11]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(myMatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10) #creates array with series 1-10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,101,20) #creates array with series 1-101 with steps of 20

array([  0,  20,  40,  60,  80, 100])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.linspace(0,5,21) #devides 0-5 by 21 times evenly

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [20]:
len(np.linspace(0,5,21))

21

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(1) #num between 0&1 different each time you run it

array([0.06203985])

In [23]:
np.random.rand(5,3)

array([[0.42564255, 0.10448948, 0.89733247],
       [0.70268659, 0.82707113, 0.36881128],
       [0.34754473, 0.00504751, 0.66545476],
       [0.46109204, 0.65787417, 0.79289597],
       [0.94207581, 0.06801575, 0.11967176]])

In [24]:
np.random.randn(5,3) #samples from a standard normal distribution (mean = 0, standard deviation of 1)

array([[ 0.70473534, -1.71144188,  0.2091544 ],
       [ 3.57595993,  0.43750878, -0.57399831],
       [ 0.2233776 ,  0.8610231 ,  0.87050736],
       [ 0.6222671 , -0.93314221, -0.79022562],
       [ 0.25868514, -0.36528352,  0.47520718]])

In [25]:
np.random.randint(0,101,(4,5)) #4x5 matrix with random numbers from between 0 & 101

array([[24, 31, 36, 19, 41],
       [35, 70,  6, 84, 79],
       [79, 43, 58, 60, 36],
       [ 1,  1, 87, 92, 19]])

In [26]:
np.random.seed(42) #seed is what random numbers are built from. As long as this number stays the same, the random numbers will be the same as before.
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [27]:
arr = np.arange(0,25)

In [28]:
arr.reshape(5,5) #.reshape will take an array and reshape it as a matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
ranarr = np.random.randint(0,101,10)

In [30]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [31]:
ranarr.max()

99

In [32]:
# Disable jedi autocompleter
%config Completer.use_jedi = False

In [33]:
ranarr.min()

2

In [34]:
ranarr.argmax() # gives position in the array the max is located(counting starts at 0)

5

In [35]:
ranarr.argmin()

7

In [36]:
ranarr.dtype

dtype('int32')

In [37]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape

(5, 5)

In [40]:
arr = np.arange(0,11)
arr
sliceOfArray = arr[0:6] #has only created pointer to existing array, not a copy.
sliceOfArray

array([0, 1, 2, 3, 4, 5])

In [41]:
sliceOfArray[:] = 99 # will modify the original array
sliceOfArray

array([99, 99, 99, 99, 99, 99])

In [42]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [43]:
arrCopy = arr.copy() #creates new complete copy of existing array.
arrCopy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
arrCopy[:] = 101
arrCopy

array([101, 101, 101, 101, 101, 101, 101, 101, 101, 101, 101])

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [92]:
arr2D = np.array([[5, 10, 15],[20, 25, 30], [35, 40, 45]])
arr2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [47]:
arr2D.shape

(3, 3)

In [96]:
arr2D[:2,1:] # ":2" means rows (start)0-2, "1:" means col 1-2(end). Slice addressing numbers are [inclusive:non-inclusive]
# in real life datasets, the rows stand for data points and the col stand for features. It is unusual to need to slice a matrix in this way

array([[10, 15],
       [25, 30]])

In [50]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
boolArr = arr > 4
boolArr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [63]:
booledArr = arr[boolArr] # makes new complete copy, not just pointer
booledArr

array([ 5,  6,  7,  8,  9, 10])

In [64]:
booledArr[:3] = 99
booledArr

array([99, 99, 99,  8,  9, 10])

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr + 5  # makes new complete copy, not just pointer

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
# divide by zero warnings and failures
arr / arr # Zero divided by anything - Gives warning about invalid value and uses "nan" (not a number) as placeholder.

C:\Users\akash\AppData\Local\Temp\ipykernel_13292\3804100558.py:2: RuntimeWarning: invalid value encountered in divide
  arr / arr # Gives warning about invalid value and uses "nan" (not a number) as placeholder.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
1/0 # Gives error

ZeroDivisionError: division by zero

In [76]:
1 / arr # Gives warning about divide by zero and uses "inf" as a placeholder. This is done because Numpy is installed.

C:\Users\akash\AppData\Local\Temp\ipykernel_13292\3071584357.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr # Gives warning


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [78]:
np.sqrt(arr) # square root

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [79]:
np.sin(arr) # give sin trig values

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [80]:
np.log(arr)

C:\Users\akash\AppData\Local\Temp\ipykernel_13292\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [81]:
arr.sum() # gives sum of all numbers in array added together

55

In [82]:
arr.mean()

5.0

In [83]:
arr.max()

10

In [84]:
arr.var() #variance

10.0

In [85]:
arr.std() #standard deviation

3.1622776601683795

In [90]:
arr2D = np.arange(0, 25).reshape(5,5)
arr2D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [87]:
arr2D.sum()

300

In [88]:
arr2D.sum(axis=0) # performs operation across axis 0, rows, adding the position in one row with the value in the same position in the next row (arr2D_00 + arr2D_10 + arr2D_20 + ...)

array([50, 55, 60, 65, 70])

In [89]:
arr2D.sum(axis=1) # performs operation across axis 1, cols, adding the position in one col with the value in the same position in the next col (arr2D_00 + arr2D_01 + arr2D_02+ ...)

array([ 10,  35,  60,  85, 110])